### ISSUE TITLE
rake

### ISSUE THREAD

**Issue by aterza** [nicb/essentia-ruby#9]
$rake

An error occurred while loading ./spec/essentia/algorithm_factory_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/essentia/algorithm_factory_spec.rb:1:in `require'
 ./spec/essentia/algorithm_factory_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/essentia/essentia_math_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/essentia/essentia_math_spec.rb:1:in `require'
 ./spec/essentia/essentia_math_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/essentia/essentia_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/essentia/essentia_spec.rb:1:in `require'
 ./spec/essentia/essentia_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/essentia/helpers/algorithms/io/monoloader_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/essentia/helpers/algorithms/io/monoloader_spec.rb:1:in `require'
 ./spec/essentia/helpers/algorithms/io/monoloader_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/essentia/helpers/algorithms/tonal/dissonance_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/essentia/helpers/algorithms/tonal/dissonance_spec.rb:1:in `require'
 ./spec/essentia/helpers/algorithms/tonal/dissonance_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/essentia/models/options_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/essentia/models/options_spec.rb:1:in `require'
 ./spec/essentia/models/options_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/essentia/streaming/source_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/essentia/streaming/source_spec.rb:1:in `require'
 ./spec/essentia/streaming/source_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/essentia/types_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/essentia/types_spec.rb:1:in `require'
 ./spec/essentia/types_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/rice/description_map_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/rice/description_map_spec.rb:1:in `require'
 ./spec/rice/description_map_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/rice/exception_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/rice/exception_spec.rb:1:in `require'
 ./spec/rice/exception_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/rice/io_base_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/rice/io_base_spec.rb:1:in `require'
 ./spec/rice/io_base_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/rice/io_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/rice/io_spec.rb:1:in `require'
 ./spec/rice/io_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/rice/modules_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/rice/modules_spec.rb:1:in `require'
 ./spec/rice/modules_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/rice/parameter_map_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/rice/parameter_map_spec.rb:1:in `require'
 ./spec/rice/parameter_map_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/rice/parameter_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/rice/parameter_spec.rb:1:in `require'
 ./spec/rice/parameter_spec.rb:1:in `<top (required)>'
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: already initialized constant Essentia::LIB_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:5: warning: previous definition of LIB_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: already initialized constant Essentia::STANDARD_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:6: warning: previous definition of STANDARD_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: already initialized constant Essentia::STREAMING_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:7: warning: previous definition of STREAMING_PATH was here
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: already initialized constant Essentia::STREAMING_ALGO_PATH
/Users/anna/Desktop/essentia-ruby/lib/essentia.rb:8: warning: previous definition of STREAMING_ALGO_PATH was here

An error occurred while loading ./spec/rice/setup_spec.rb.
Failure/Error:
    version
    essentia_ruby_wrap
    helpers
    models
  ).each { |f| require File.join(Essentia::LIB_PATH, f) }

LoadError:
  cannot load such file -- /Users/anna/Desktop/essentia-ruby/lib/essentia/essentia_ruby_wrap
 ./lib/essentia.rb:16:in `require'
 ./lib/essentia.rb:16:in `block in <top (required)>'
 ./lib/essentia.rb:16:in `each'
 ./lib/essentia.rb:16:in `<top (required)>'
 ./spec/spec_helper.rb:3:in `require'
 ./spec/spec_helper.rb:3:in `<top (required)>'
 ./spec/rice/setup_spec.rb:1:in `require'
 ./spec/rice/setup_spec.rb:1:in `<top (required)>'

Finished in 0.00027 seconds (files took 0.18942 seconds to load)
0 examples, 0 failures, 16 errors occurred outside of examples

**Comment by aterza** [comment]
rake compile, then
$rake


An error occurred while loading ./spec/essentia/algorithm_factory_spec.rb.
Failure/Error:
  describe Essentia::AlgorithmFactory do
  
    before :example do
      @af = Essentia::AlgorithmFactory.instance
    end
  
    it 'responds to the create method' do
      expect(@af.respond_to?(:create)).to be(true)
    end
  

NameError:
  uninitialized constant Essentia::AlgorithmFactory
  ./spec/essentia/algorithm_factory_spec.rb:3:in `<top (required)>'

An error occurred while loading ./spec/essentia/types_spec.rb.
Failure/Error:
  describe Essentia::AnyVector do
  
    before :example do
      @mixed_bag = [23, 16.0, 'whatever', ATestObject.new]
    end
  
    it 'can be created with different arguments' do
      expect((av = Essentia::AnyVector.new).class).to be(Essentia::AnyVector)
      expect((av = Essentia::AnyVector.new(23)).class).to be(Essentia::AnyVector)
      expect((av = Essentia::AnyVector.new(@mixed_bag)).class).to be(Essentia::AnyVector)

NameError:
  uninitialized constant Essentia::AnyVector
  ./spec/essentia/types_spec.rb:5:in `<top (required)>'


Finished in 0.00027 seconds (files took 1.47 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

**Comment by nicb** [comment]
Not all specs work yet. Only some of the ones in `spec/rice` do, and not even all of them. I am working on it, and help is greatly appreciated there. To run the specs in `spec/rice`, run:

```bash
$ rake spec SPEC=spec/rice/*_spec.rb
```
